name: go_weather
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  easy_autocomplete: ^1.6.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  get: ^4.6.5
  google_fonts: ^5.1.0
  intl: ^0.18.1
  location: ^4.4.0
  material_symbols_icons: ^4.2661.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/weather/day/
    - assets/weather/night/
