name: go_weather
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.17
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  location: ^8.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/weather/day/
    - assets/weather/night/
    - assets/icons/
    - assets/lottie/
